name: GitHub Actions PR
on: [pull_request]
jobs:
  test-core:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build core
      run: cargo build --verbose --no-default-features
    - name: Test core
      run: cargo test --verbose --no-default-features

  test-features:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build features
      run: cargo build --verbose --all-features
    - name: Test featuers
      run: cargo test --verbose --all-features
